### ISSUE TITLE
Criar prototipação da tela de cadastramento de usuários

### ISSUE THREAD

**Issue by cezac** [cezac/Find-Your-Land#9]

**Comment by breno-jesus-fernandes** [comment]
![Image](https://github.com/cezac/Find-Your-Land/assets/32203685/df1a2079-898a-4410-9dfb-67c33bbe2dc4)

**Comment by breno-jesus-fernandes** [comment]
https://www.figma.com/proto/o6p4rriIuhP2Z32YqVom11/Find-Your-Land?type=design&node-id=109-88&t=gSs9xK0SHSi9YTDh-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=109%3A88&mode=design
